graalify script more general WRT native-image location

diff --git a/bin/graalify b/bin/graalify
--- a/bin/graalify
+++ b/bin/graalify
@@ -2,8 +2,8 @@
 
 # Build self-contained executable using GraalVM.
 
-if [ -z "$GRAALVM_HOME" ]; then
-  echo 'Please set GRAALVM_HOME'
+if ! command -v native-image &> /dev/null; then
+  echo 'GraalVM native-image command not found'
   exit 1
 fi
 
@@ -16,11 +16,8 @@ mkdir -p target
 # Compile Clojure:
 clojure -M -e "(compile 'xnav.main)"
 
-# Ensure GraalVM native-image program is installed:
-"$GRAALVM_HOME/bin/gu" install native-image
-
 # Build stand-alone binary:
-"$GRAALVM_HOME/bin/native-image" \
+native-image \
   -cp "$(clojure -Spath):classes" \
   -H:Name=target/xnav \
   -H:+ReportExceptionStackTraces \
